version: '3.7'
services:

  db:
    image: postgres:12
    command: postgres -c 'max_connections=500'
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${MYSQL_DATABASE}
      POSTGRES_USER: ${MYSQL_USER}
      POSTGRES_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    # container for UI database management
  phpmyadmin:
    image: dpage/pgadmin4
    ports:
      - ${PHPADMIN_PORT}:80
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    restart: always

  laravel-blog:
    build:
      context: ./docker/php
    container_name: laravel-blog
    volumes:
      - ./laravel/:/home/source/main
    working_dir: /home/source/main
    depends_on:
      - db
    restart: always

  nginx:
    build:
      context: ./docker/nginx
    container_name: api-nginx
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    depends_on:
      - laravel-blog
      - db
    volumes:
      - ./laravel/public:/home/source/main/public
      - ./laravel/storage/app/public/avatars:/home/source/main/storage/app/public/avatars
    restart: always

  redis:
    image: docker.io/bitnami/redis:7.2
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=redis123
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - ./redis_data:/bitnami/redis/data
    restart: always
    
volumes:
  postgres-volumes:

networks:
  default:
    name: laravel-blog-netword
